# Change these first
owner: sipamungkas # Your GitHub organization or username, where this repository lives
repo: upptime-stats # The name of this repository

sites:
  - name: Daily Language Dev API
    url: https://dl-api-dev.app-dev.my.id/api/v1/ping
  - name: Daily Langauge Dev Dashboard
    url: http://dl-dev.app-dev.my.id/
  - name: Daily Langauge Prod API
    url: https://api.dailylanguage.my.id/api/v1/ping
  - name: Daily Language Prod Dashboard
    url: https://dailylanguage.my.id
  - name: DL Prod Server
    check: "tcp-ping"
    url: "103.127.132.76"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.pods.my.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Managed Server Status Sipamungkas Project** powered by Upptime."
  introMessage: This is a status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  workflowSchedule:
    graphs: "*/15 * * * *"
    responseTime: "*/15 * * * *"
    staticSite: "*/15 * * * *"
    summary: "*/15 * * * *"
    updateTemplate: "*/15 * * * *"
    updates: "*/15 * * * *"
    uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
